# Generated by Django 6.0.1 on 2026-02-07 08:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import utils.paths
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'This username already exists'}, help_text='Enter a unique username (letters, numbers, dot, or underline, up to 30 characters).', max_length=30, unique=True, validators=[utils.validators.UsernameValidator()])),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'This email already exists'}, help_text='Enter a unique email.', max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(help_text='Enter a valid first name (letters, up to 15 characters).', max_length=15, validators=[utils.validators.NameValidator('First name')])),
                ('last_name', models.CharField(help_text='Enter a valid last name (letters, up to 15 characters).', max_length=15, validators=[utils.validators.NameValidator('Last name')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'This phone number already exists'}, help_text='Enter your phone number in international format, e.g., +981234567890', max_length=128, region=None, unique=True)),
                ('website_url', models.URLField(blank=True, help_text='Enter a website url (https://, up to 50 characters).', max_length=50, null=True, validators=[utils.validators.URLValidator()])),
                ('bio', models.TextField(blank=True, help_text='Enter your bio (up to 200 characters).', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, help_text='Enter your profile image (png, jpg, jpeg, gif).', null=True, upload_to=utils.paths.get_user_profile_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
